server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: finanzas
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: never

app:
  jwt:
    secret: bXktc3VwZXItc2VjcmV0LWtleS1wYXJhLXNwcmluZy1ib290LWZpbmFuemFzLTIwMjYtYXBpLXNlZ3VyYQ==
    expiration-ms: 86400000
